### ISSUE TITLE
Extending AbilityDefinitionCurse or AbilityDefinitionCursecreep gives ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by karlek** [wurstscript/WurstStdlib2#120]
Faulty code:
```wurst
class SmokeBomb extends AbilityDefinitionCurse
    construct(int id)
        super(id)

        setButtonPositionNormalX(3)
        setButtonPositionNormalY(2)

        setEffectSound("")

        setManaCost(1, 0)
        setChancetoMiss(1, 0.3)
        setDurationNormal(1, 5)
        setArtTarget(Abilities.tornado_Target)
        // setTargetsAllowed(1, commaList(
        //     TargetsAllowed.structure,
        //     TargetsAllowed.invulnerable
        // ))

@compiletime function anotherName()
    new SmokeBomb(ID_SMOKE_BOMB)
```

Stacktrace:
```
initializing workspace
initialization done!
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at de.peeeq.wurstio.objectreader.BinaryDataOutputStream.writeString(BinaryDataOutputStream.java:53)
	at de.peeeq.wurstio.objectreader.ObjectModification.writeToStream(ObjectModification.java:89)
	at de.peeeq.wurstio.objectreader.ObjectDefinition.writeToStream(ObjectDefinition.java:45)
	at de.peeeq.wurstio.objectreader.ObjectTable.writeToStream(ObjectTable.java:46)
	at de.peeeq.wurstio.objectreader.ObjectFile.writeTo(ObjectFile.java:84)
	at de.peeeq.wurstio.objectreader.ObjectFile.writeToByteArray(ObjectFile.java:73)
	at de.peeeq.wurstio.intermediateLang.interpreter.ProgramStateIO.writebackObjectFile(ProgramStateIO.java:218)
	at de.peeeq.wurstio.intermediateLang.interpreter.ProgramStateIO.writeBack(ProgramStateIO.java:188)
	at de.peeeq.wurstscript.intermediatelang.interpreter.ILInterpreter.writebackGlobalState(ILInterpreter.java:204)
	at de.peeeq.wurstio.CompiletimeFunctionRunner.run(CompiletimeFunctionRunner.java:102)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileMap(MapRequest.java:144)
	at de.peeeq.wurstio.languageserver.requests.RunMap.compileScript(RunMap.java:238)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:85)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$108(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Thread.java:748)
java.lang.Error: java.lang.ArrayIndexOutOfBoundsException
	at de.peeeq.wurstio.intermediateLang.interpreter.ProgramStateIO.writebackObjectFile(ProgramStateIO.java:233)
	at de.peeeq.wurstio.intermediateLang.interpreter.ProgramStateIO.writeBack(ProgramStateIO.java:188)
	at de.peeeq.wurstscript.intermediatelang.interpreter.ILInterpreter.writebackGlobalState(ILInterpreter.java:204)
	at de.peeeq.wurstio.CompiletimeFunctionRunner.run(CompiletimeFunctionRunner.java:102)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileMap(MapRequest.java:144)
	at de.peeeq.wurstio.languageserver.requests.RunMap.compileScript(RunMap.java:238)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:85)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$108(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at de.peeeq.wurstio.objectreader.BinaryDataOutputStream.writeString(BinaryDataOutputStream.java:53)
	at de.peeeq.wurstio.objectreader.ObjectModification.writeToStream(ObjectModification.java:89)
	at de.peeeq.wurstio.objectreader.ObjectDefinition.writeToStream(ObjectDefinition.java:45)
	at de.peeeq.wurstio.objectreader.ObjectTable.writeToStream(ObjectTable.java:46)
	at de.peeeq.wurstio.objectreader.ObjectFile.writeTo(ObjectFile.java:84)
	at de.peeeq.wurstio.objectreader.ObjectFile.writeToByteArray(ObjectFile.java:73)
	at de.peeeq.wurstio.intermediateLang.interpreter.ProgramStateIO.writebackObjectFile(ProgramStateIO.java:218)
	... 11 more
Sep 18, 2018 11:02:49 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.RuntimeException: de.peeeq.wurstio.languageserver.requests.RequestFailedException: Could not compile project (error in running compiletime functions/expressions): Error in File CrowForm.wurst line 25:
 java.lang.ArrayIndexOutOfBoundsException
java.util.concurrent.CompletionException: java.lang.RuntimeException: de.peeeq.wurstio.languageserver.requests.RequestFailedException: Could not compile project (error in running compiletime functions/expressions): Error in File CrowForm.wurst line 25:
 java.lang.ArrayIndexOutOfBoundsException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.handleException(MapRequest.java:63)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$110(LanguageWorker.java:272)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$108(LanguageWorker.java:170)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:28)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:145)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: de.peeeq.wurstio.languageserver.requests.RequestFailedException: Could not compile project (error in running compiletime functions/expressions): Error in File CrowForm.wurst line 25:
 java.lang.ArrayIndexOutOfBoundsException
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileMap(MapRequest.java:177)
	at de.peeeq.wurstio.languageserver.requests.RunMap.compileScript(RunMap.java:238)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:85)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more
Caused by: de.peeeq.wurstio.languageserver.requests.RequestFailedException: Could not compile project (error in running compiletime functions/expressions): Error in File CrowForm.wurst line 25:
 java.lang.ArrayIndexOutOfBoundsException
	at de.peeeq.wurstio.languageserver.requests.MapRequest.compileMap(MapRequest.java:149)
	... 7 more
```

**Comment by karlek** [comment]
It is worth stating that DrunkenHaze spells `setChancetoMiss` as `setChanceToMiss` and doesn't have the same problem.

This could also be a compiler issue, if so it can be moved to WurstScript

**Comment by Frotty** [comment]
hm yeah, looks like a compiler issue. Would probably be solved by using wc3libs instead of wursts own custom stuff, but it's not so easily replaced.

**Comment by Frotty** [comment]
do you have an easy fix idea @peq ?

**Comment by peq** [comment]
```
public class AbilityDefinitionCurse extends AbilityDefinition
	construct(int newAbilityId)
		super(newAbilityId, AbilityIds.curse)

	function setChancetoMiss(int level, real value)
		def.setLvlDataUnreal("Crs", level, 1, value)

	function presetChancetoMiss(RealLevelClosure lc)
		def.setLevelsDataUnreal("Crs", lvls, 1, lc)
		addTooltipProperty("ChancetoMiss", lc)

```

The modification id should always have 4 chars but here `"Crs"` only has 3.

**Comment by peq** [comment]
Actually it seems to be "Crs" in `AbilityMetaData.csv`, so it had to be changed in the Wurst compiler. It's the only modification id that is not 4 characters long, so we did not catch this yet. The compiler will now just add `\0` at the end if the id is too short and it seems to work when loading the map in WE.

**Comment by karlek** [comment]
Wow, nice find!
